# Site Settings
title: Elapsed Time Adder
description: Add and subtract elapsed time on iOS, iPadOS, and macOS. Free app by Allison Sheridan.
url: https://timeadder.podfeet.com

# Build Settings
plugins:
  - jekyll-autoprefixer

# Settings for the autoprefixer plugin
autoprefixer:
  browsers:
    - last 4 versions
    - Safari > 2
